### ISSUE TITLE
Failing tests with the JavaCheckVerifier

### ISSUE THREAD

**Issue by lmarniazman** [devonfw/sonar-devon4j-plugin#48]
When running tests with the JavaCheckVerifier in the new beta25 version of the devonfw-ide, there is an error saying 
`Unable to create symbol table for <Class>`

After updating the sonar dependencies (sonar.version to 8.0 and java.plugin.version to 5.14.0.18788), I got a new error saying there was a NoClassDefFoundError on 
`org/sonar/api/batch/sensor/internal/SensorContextTester`.
Also there is now an error in the DevonSonarDefinition.java, because it fails to resolve an import from org.sonar.squidbridge.

After testing it with the old dependency versions and in the 3.1.0 Devonfw distribution, some tests work and some fail with the error of being unable to analyze certain test files.

I hope this will be resolved by updating some dependencies, I will look into it further tomorrow.

**Comment by lmarniazman** [comment]
Tests work when setting sonar.version to 6.7.7. I will try to update this to the highest possible version. We will have to do some refactoring when we wanto to update the sonar version to 8.0, as some classes are deprecated there.

**Comment by lmarniazman** [comment]
Updated dependencies with PR #47 
Removed reference to deprecated method in PR #53
